#############################################################################
# Makefile for building: Local_CS1D_project_2.app/Contents/MacOS/Local_CS1D_project_2
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  Local_CS1D_project_2.pro
# Template: app
# Command: /Applications/QT/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile Local_CS1D_project_2.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Applications/QT/5.4/clang_64/mkspecs/macx-clang -I. -I/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Applications/QT/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Applications/QT/5.4/clang_64/lib
QMAKE         = /Applications/QT/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Local_CS1D_project_21.0.0
DISTDIR = /Users/austinrosario/Desktop/CS1D\ group\ project\ 2/Local_Project/Local_CS1D_project_2/.tmp/Local_CS1D_project_21.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Applications/QT/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/QT/5.4/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		baseball_team_class.cpp \
		baseball_stadium_class.cpp \
		read_stadiums_from_file.cpp \
		view_stadiums.cpp moc_mainwindow.cpp \
		moc_view_stadiums.cpp
OBJECTS       = main.o \
		mainwindow.o \
		baseball_team_class.o \
		baseball_stadium_class.o \
		read_stadiums_from_file.o \
		view_stadiums.o \
		moc_mainwindow.o \
		moc_view_stadiums.o
DIST          = stadium_data.txt \
		/Applications/QT/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/QT/5.4/clang_64/mkspecs/qdevice.pri \
		/Applications/QT/5.4/clang_64/mkspecs/features/device_config.prf \
		/Applications/QT/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/unix.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/mac.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/macx.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/clang.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/QT/5.4/clang_64/mkspecs/qconfig.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/qt_config.prf \
		/Applications/QT/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/QT/5.4/clang_64/mkspecs/features/spec_post.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/default_pre.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/default_post.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/warn_on.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/qt.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/resources.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/moc.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/uic.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/exceptions.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/yacc.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/lex.prf \
		Local_CS1D_project_2.pro mainwindow.h \
		baseball_team_class.h \
		baseball_stadium_class.h \
		headers.h \
		view_stadiums.h main.cpp \
		mainwindow.cpp \
		baseball_team_class.cpp \
		baseball_stadium_class.cpp \
		read_stadiums_from_file.cpp \
		view_stadiums.cpp
QMAKE_TARGET  = Local_CS1D_project_2
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Local_CS1D_project_2.app/Contents/MacOS/Local_CS1D_project_2

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h ui_view_stadiums.h $(OBJECTS)  
	@test -d Local_CS1D_project_2.app/Contents/MacOS/ || mkdir -p Local_CS1D_project_2.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Local_CS1D_project_2.pro /Applications/QT/5.4/clang_64/mkspecs/macx-clang/qmake.conf /Applications/QT/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/QT/5.4/clang_64/mkspecs/qdevice.pri \
		/Applications/QT/5.4/clang_64/mkspecs/features/device_config.prf \
		/Applications/QT/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/unix.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/mac.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/macx.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/clang.conf \
		/Applications/QT/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/QT/5.4/clang_64/mkspecs/qconfig.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/QT/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/qt_config.prf \
		/Applications/QT/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/QT/5.4/clang_64/mkspecs/features/spec_post.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/default_pre.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/default_post.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/warn_on.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/qt.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/resources.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/moc.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/uic.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/exceptions.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/yacc.prf \
		/Applications/QT/5.4/clang_64/mkspecs/features/lex.prf \
		Local_CS1D_project_2.pro \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/QT/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile Local_CS1D_project_2.pro
/Applications/QT/5.4/clang_64/mkspecs/features/spec_pre.prf:
/Applications/QT/5.4/clang_64/mkspecs/qdevice.pri:
/Applications/QT/5.4/clang_64/mkspecs/features/device_config.prf:
/Applications/QT/5.4/clang_64/mkspecs/common/shell-unix.conf:
/Applications/QT/5.4/clang_64/mkspecs/common/unix.conf:
/Applications/QT/5.4/clang_64/mkspecs/common/mac.conf:
/Applications/QT/5.4/clang_64/mkspecs/common/macx.conf:
/Applications/QT/5.4/clang_64/mkspecs/common/gcc-base.conf:
/Applications/QT/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/QT/5.4/clang_64/mkspecs/common/clang.conf:
/Applications/QT/5.4/clang_64/mkspecs/common/clang-mac.conf:
/Applications/QT/5.4/clang_64/mkspecs/qconfig.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/QT/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/QT/5.4/clang_64/mkspecs/features/qt_functions.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/qt_config.prf:
/Applications/QT/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/QT/5.4/clang_64/mkspecs/features/spec_post.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/default_pre.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/resolve_config.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/default_post.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/warn_on.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/qt.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/resources.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/moc.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/uic.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/unix/thread.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/mac/rez.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/exceptions.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/yacc.prf:
/Applications/QT/5.4/clang_64/mkspecs/features/lex.prf:
Local_CS1D_project_2.pro:
/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/QT/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/QT/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile Local_CS1D_project_2.pro

qmake_all: FORCE

Local_CS1D_project_2.app/Contents/PkgInfo: 
	@test -d Local_CS1D_project_2.app/Contents || mkdir -p Local_CS1D_project_2.app/Contents
	@$(DEL_FILE) Local_CS1D_project_2.app/Contents/PkgInfo
	@echo "APPL????" >Local_CS1D_project_2.app/Contents/PkgInfo
Local_CS1D_project_2.app/Contents/Resources/empty.lproj: 
	@test -d Local_CS1D_project_2.app/Contents/Resources || mkdir -p Local_CS1D_project_2.app/Contents/Resources
	@touch Local_CS1D_project_2.app/Contents/Resources/empty.lproj
	
Local_CS1D_project_2.app/Contents/Info.plist: 
	@test -d Local_CS1D_project_2.app/Contents || mkdir -p Local_CS1D_project_2.app/Contents
	@$(DEL_FILE) Local_CS1D_project_2.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,xcode.Local_CS1D_project_2,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Local_CS1D_project_2,g" -e "s,@TYPEINFO@,????,g" /Applications/QT/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >Local_CS1D_project_2.app/Contents/Info.plist

all: Makefile \
		Local_CS1D_project_2.app/Contents/PkgInfo \
		Local_CS1D_project_2.app/Contents/Resources/empty.lproj \
		Local_CS1D_project_2.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h baseball_team_class.h baseball_stadium_class.h headers.h view_stadiums.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp baseball_team_class.cpp baseball_stadium_class.cpp read_stadiums_from_file.cpp view_stadiums.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui view_stadiums.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Local_CS1D_project_2.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_view_stadiums.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_view_stadiums.cpp
moc_mainwindow.cpp: /Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		mainwindow.h
	/Applications/QT/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Applications/QT/5.4/clang_64/mkspecs/macx-clang -I'/Users/austinrosario/Desktop/CS1D group project 2/Local_Project/Local_CS1D_project_2' -I/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Applications/QT/5.4/clang_64/lib/QtGui.framework/Headers -I/Applications/QT/5.4/clang_64/lib/QtCore.framework/Headers -F/Applications/QT/5.4/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_view_stadiums.cpp: /Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		view_stadiums.h
	/Applications/QT/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Applications/QT/5.4/clang_64/mkspecs/macx-clang -I'/Users/austinrosario/Desktop/CS1D group project 2/Local_Project/Local_CS1D_project_2' -I/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Applications/QT/5.4/clang_64/lib/QtGui.framework/Headers -I/Applications/QT/5.4/clang_64/lib/QtCore.framework/Headers -F/Applications/QT/5.4/clang_64/lib view_stadiums.h -o moc_view_stadiums.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_view_stadiums.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_view_stadiums.h
ui_mainwindow.h: mainwindow.ui
	/Applications/QT/5.4/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_view_stadiums.h: view_stadiums.ui
	/Applications/QT/5.4/clang_64/bin/uic view_stadiums.ui -o ui_view_stadiums.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		baseball_stadium_class.h \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		baseball_team_class.h \
		headers.h \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		view_stadiums.h \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

baseball_team_class.o: baseball_team_class.cpp baseball_team_class.h \
		baseball_stadium_class.h \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baseball_team_class.o baseball_team_class.cpp

baseball_stadium_class.o: baseball_stadium_class.cpp baseball_stadium_class.h \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baseball_stadium_class.o baseball_stadium_class.cpp

read_stadiums_from_file.o: read_stadiums_from_file.cpp baseball_team_class.h \
		baseball_stadium_class.h \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		/Applications/QT/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o read_stadiums_from_file.o read_stadiums_from_file.cpp

view_stadiums.o: view_stadiums.cpp view_stadiums.h \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/QT/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		ui_view_stadiums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view_stadiums.o view_stadiums.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view_stadiums.o: moc_view_stadiums.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view_stadiums.o moc_view_stadiums.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

